### ISSUE TITLE
Different block regeneration values to each region

### ISSUE THREAD

**Issue by MrDuartePT** [Aurorion/BlockRegen#10]
I am using this plugin in my server to regenerate ores inside caves and dungeons create by me and do it in floor, 1º floor, 2º floor, and so on. I would know if its possible to get different percentage for each region/floor or its a feature you can add in the future. I send the Blocklist.yml with my idea.

`# BlockRegen
Blocks:
region: frist_floor #name of the region/floor for exemple
  COBBLESTONE:
  replace-block: BEDROCK
  regen-delay:
    low: 7
    high: 8
  natural-break: true
  drop-item.drop-naturally: true
  regenerate-into: IRON_ORE:17;COAL:25;COBBLESTONE:7;DIORITE:7;GRANITE:7;ANDESITE:7;GRAVEL:15;STONE:15
  DIORITE:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  GRANITE:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  ANDESITE:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  GRAVEL:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  STONE:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  COAL:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true
  IRON_ORE:
  replace-block: COBBLESTONE
  natural-break: true
  drop-item.drop-naturally: true

region: second_floor #name of the region/floor for exemple
#
#Same code that above but with different percentages
#
`

Best regards,
MrDuartePT

**Comment by Wertik** [comment]
Even though this repository and the original author are no longer active I've been continuing to update the plugin and it is occasionally updated on spigotmc. For the latest release head over to https://github.com/Wertik/BlockRegen. As for your feature request, this behavior is already planned and close to completion.

Trello board: https://trello.com/b/FfsHxZUW/blockregen

Thanks for the suggestion. ;)

**Comment by MrDuartePT** [comment]
I like the amazing features you add on the plugin and the great compatible have with 1.12 version is the same version I use in my spigot server. I gonna star your repository and wait for this feature I can try to help but I don't know java just C/C++.

Thanks for you response, stay safe and have I nice day
